"use client";

import analytics from "@/public/data/analytics.json";
import Image from "next/image";
import {
  Activity,
  Camera,
  Globe2,
  Map,
  Radio,
  ShieldAlert,
} from "lucide-react";

export function AdvancedMining() {
  const spatial = analytics.spatial;
  const stream = analytics.streamMining;
  const image = analytics.imagePipeline;
  const web = analytics.webMining;
  return (
    <section className="workspace-panel">
      <div className="workspace-hero">
        <span className="eyebrow">CO5 · advanced mining</span>
        <h1>Patterns beyond rows and labels.</h1>
        <p>
          Spatial, web, stream and multimedia experiments are generated by the
          same versioned pipeline and carry their own evaluation evidence.
        </p>
      </div>
      <div className="method-grid advanced-grid">
        <article className="panel">
          <span className="eyebrow">
            <Map size={15} /> Spatial mining
          </span>
          <h2>Geographic autocorrelation</h2>
          <strong className="advanced-value">{spatial.globalMoranI}</strong>
          <p className="method-copy">
            Global Moran&apos;s I across valid campus coordinates. Values near
            zero indicate little global spatial structure.
          </p>
          <small>
            {spatial.hotspots.length} local hotspot facilities profiled
          </small>
        </article>
        <article className="panel">
          <span className="eyebrow">
            <Radio size={15} /> Stream mining
          </span>
          <h2>Windowed drift monitor</h2>
          <strong className="advanced-value">{stream.driftWindowCount}</strong>
          <p className="method-copy">
            flagged windows from {stream.windowCount} sliding windows using
            Jensen–Shannon divergence.
          </p>
          <small>Retraining policy · {stream.operationalPolicy}</small>
        </article>
        <article className="panel">
          <span className="eyebrow">
            <Globe2 size={15} /> Web usage mining
          </span>
          <h2>Interaction funnels</h2>
          <strong className="advanced-value">
            {web.eventCount.toLocaleString()}
          </strong>
          <p className="method-copy">
            synthetic privacy-safe events used for route transitions, dwell time
            and report-conversion analysis.
          </p>
          <small>
            Top path · {web.topTransitions[0]?.from} →{" "}
            {web.topTransitions[0]?.to}
          </small>
        </article>
        <article className="panel">
          <span className="eyebrow">
            <Camera size={15} /> Multimedia mining
          </span>
          <h2>Visual evidence classifier</h2>
          <strong className="advanced-value">{(image.macroF1 * 100).toFixed(2)}%</strong>
          <p className="method-copy">
            Macro-F1 on an untouched visual holdout using image-derived texture,
            edge and colour features.
          </p>
          <small>
            {image.datasetSize} labelled images · duplicate similarity checked
          </small>
        </article>
      </div>
      <article className="panel evidence-gallery">
        <div className="panel-head">
          <div>
            <span className="eyebrow">Multimodal evidence</span>
            <h2>Processed visual classes</h2>
          </div>
          <span className="dataset-pill">
            <Activity size={14} /> evaluated holdout
          </span>
        </div>
        <div>
          {[
            "cleanliness_hazard",
            "equipment_fault",
            "infrastructure_damage",
            "normal",
          ].map((name) => (
            <figure key={name}>
              <Image
                src={`/images/evidence/multimedia-${name}.jpg`}
                width={360}
                height={220}
                alt={`Synthetic ${name.replaceAll("_", " ")} evidence`}
              />
              <figcaption>{name.replaceAll("_", " ")}</figcaption>
            </figure>
          ))}
        </div>
      </article>
      <p className="r-note warning-note">
        <ShieldAlert size={18} />
        <b>Scope note:</b> these are controlled synthetic benchmarks, not claims
        about real students or campus conditions. Spatial coordinates are
        facility centroids and web sessions contain no identifiers.
      </p>
    </section>
  );
}
